import { Box } from "@mui/material";
import { FlexProps } from "./types";
import styled from "@emotion/styled";

const FlexBox = styled(Box)(
  ({
    alignItems,
    justifyContent,
    alignSelf,
    justifySelf,
    gap,
    width,
    height,
    aspectRatio,
    backgroundColor,
    borderColor,
    borderRadius,
    flexDirection,
    margin,
    marginLeft,
    marginRight,
    marginTop,
    marginBottom,
    padding,
    paddingLeft,
    paddingRight,
    paddingTop,
    paddingBottom,
    boxShadow,
    position,
    top,
    bottom,
    left,
    right,
  }: FlexProps) => ({
    display: "flex",
    alignItems,
    justifyContent,
    alignSelf,
    justifySelf,
    gap,
    borderRadius,
    borderColor,
    width,
    flexDirection,
    backgroundColor,
    height,
    aspectRatio,
    margin,
    marginLeft,
    marginRight,
    marginTop,
    marginBottom,
    padding,
    paddingLeft,
    paddingRight,
    paddingTop,
    paddingBottom,
    position,
    top,
    bottom,
    left,
    right,
    boxShadow,
  })
);

export default FlexBox;
